#############################################################################
# Makefile for building: bedcoll
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  bedcollqt.pro
# Template: app
# Command: /home/kaiyin/Qt5/5.3/gcc_64/bin/qmake -spec linux-clang CONFIG+=debug -o Makefile bedcollqt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -D_FILE_OFFSET_BITS=64 -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../../Qt5/5.3/gcc_64/mkspecs/linux-clang -I. -I/usr/include/c++/4.8 -I/usr/include/boost -I../../../Qt5/5.3/gcc_64/include -I../../../Qt5/5.3/gcc_64/include/QtCore -I.
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/home/kaiyin/Qt5/5.3/gcc_64 -Wl,-rpath,/home/kaiyin/Qt5/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -lboost_system -lboost_filesystem -lboost_program_options -L/home/kaiyin/Qt5/5.3/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/kaiyin/Qt5/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/util.cpp \
		src/bedcoll.cpp \
		src/main.cpp 
OBJECTS       = util.o \
		bedcoll.o \
		main.o
DIST          = ../../../Qt5/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/clang.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/linux-clang/qmake.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/resources.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/moc.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/lex.prf \
		bedcollqt.pro src/util.cpp \
		src/bedcoll.cpp \
		src/main.cpp
QMAKE_TARGET  = bedcoll
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = bedcoll


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bedcollqt.pro ../../../Qt5/5.3/gcc_64/mkspecs/linux-clang/qmake.conf ../../../Qt5/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/clang.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/linux-clang/qmake.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/resources.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/moc.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/lex.prf \
		bedcollqt.pro \
		/home/kaiyin/Qt5/5.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-clang CONFIG+=debug -o Makefile bedcollqt.pro
../../../Qt5/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt5/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/linux.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/clang.conf:
../../../Qt5/5.3/gcc_64/mkspecs/qconfig.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt5/5.3/gcc_64/mkspecs/linux-clang/qmake.conf:
../../../Qt5/5.3/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/default_post.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/qt.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/resources.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/moc.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/yacc.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/lex.prf:
bedcollqt.pro:
/home/kaiyin/Qt5/5.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-clang CONFIG+=debug -o Makefile bedcollqt.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/bedcoll1.0.0 || mkdir -p .tmp/bedcoll1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/bedcoll1.0.0/ && $(COPY_FILE) --parents src/collgen_memo.h src/util.h src/bedcoll.h src/error_enum.h .tmp/bedcoll1.0.0/ && $(COPY_FILE) --parents src/util.cpp src/bedcoll.cpp src/main.cpp .tmp/bedcoll1.0.0/ && (cd `dirname .tmp/bedcoll1.0.0` && $(TAR) bedcoll1.0.0.tar bedcoll1.0.0 && $(COMPRESS) bedcoll1.0.0.tar) && $(MOVE) `dirname .tmp/bedcoll1.0.0`/bedcoll1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/bedcoll1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

util.o: src/util.cpp src/util.h \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/random \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/bits/random.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/bits/random.tcc \
		/usr/include/c++/4.8/numeric \
		/usr/include/c++/4.8/bits/stl_numeric.h \
		/usr/include/c++/4.8/parallel/numeric \
		/usr/include/c++/4.8/parallel/numericfwd.h \
		/usr/include/c++/4.8/parallel/iterator.h \
		/usr/include/c++/4.8/parallel/for_each.h \
		/usr/include/c++/4.8/parallel/par_loop.h \
		/usr/include/c++/4.8/parallel/omp_loop.h \
		/usr/include/c++/4.8/parallel/workstealing.h \
		/usr/include/c++/4.8/parallel/random_number.h \
		/usr/include/c++/4.8/tr1/random \
		/usr/include/c++/4.8/tr1/cmath \
		/usr/include/c++/4.8/tr1/gamma.tcc \
		/usr/include/c++/4.8/tr1/special_function_util.h \
		/usr/include/c++/4.8/tr1/bessel_function.tcc \
		/usr/include/c++/4.8/tr1/beta_function.tcc \
		/usr/include/c++/4.8/tr1/ell_integral.tcc \
		/usr/include/c++/4.8/tr1/exp_integral.tcc \
		/usr/include/c++/4.8/tr1/hypergeometric.tcc \
		/usr/include/c++/4.8/tr1/legendre_function.tcc \
		/usr/include/c++/4.8/tr1/modified_bessel_func.tcc \
		/usr/include/c++/4.8/tr1/poly_hermite.tcc \
		/usr/include/c++/4.8/tr1/poly_laguerre.tcc \
		/usr/include/c++/4.8/tr1/riemann_zeta.tcc \
		/usr/include/c++/4.8/tr1/random.h \
		/usr/include/c++/4.8/tr1/random.tcc \
		/usr/include/c++/4.8/parallel/for_each_selectors.h \
		/usr/include/c++/4.8/parallel/partial_sum.h \
		/usr/include/c++/4.8/parallel/algorithm \
		/usr/include/c++/4.8/parallel/algo.h \
		/usr/include/c++/4.8/parallel/sort.h \
		/usr/include/c++/4.8/parallel/checkers.h \
		/usr/include/c++/4.8/parallel/multiway_mergesort.h \
		/usr/include/c++/4.8/parallel/multiway_merge.h \
		/usr/include/c++/4.8/parallel/losertree.h \
		/usr/include/c++/4.8/parallel/multiseq_selection.h \
		/usr/include/c++/4.8/queue \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/include/c++/4.8/debug/deque \
		/usr/include/c++/4.8/profile/deque \
		/usr/include/c++/4.8/bits/stl_queue.h \
		/usr/include/c++/4.8/parallel/quicksort.h \
		/usr/include/c++/4.8/parallel/partition.h \
		/usr/include/c++/4.8/parallel/balanced_quicksort.h \
		/usr/include/c++/4.8/parallel/queue.h \
		/usr/include/c++/4.8/parallel/omp_loop_static.h \
		/usr/include/c++/4.8/parallel/search.h \
		/usr/include/c++/4.8/parallel/random_shuffle.h \
		/usr/include/c++/4.8/parallel/merge.h \
		/usr/include/c++/4.8/parallel/unique_copy.h \
		/usr/include/c++/4.8/parallel/set_operations.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o src/util.cpp

bedcoll.o: src/bedcoll.cpp src/bedcoll.h \
		/usr/include/c++/4.8/iostream \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/random \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/bits/random.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/bits/random.tcc \
		/usr/include/c++/4.8/numeric \
		/usr/include/c++/4.8/bits/stl_numeric.h \
		/usr/include/c++/4.8/parallel/numeric \
		/usr/include/c++/4.8/parallel/numericfwd.h \
		/usr/include/c++/4.8/parallel/iterator.h \
		/usr/include/c++/4.8/parallel/for_each.h \
		/usr/include/c++/4.8/parallel/par_loop.h \
		/usr/include/c++/4.8/parallel/omp_loop.h \
		/usr/include/c++/4.8/parallel/workstealing.h \
		/usr/include/c++/4.8/parallel/random_number.h \
		/usr/include/c++/4.8/tr1/random \
		/usr/include/c++/4.8/tr1/cmath \
		/usr/include/c++/4.8/tr1/gamma.tcc \
		/usr/include/c++/4.8/tr1/special_function_util.h \
		/usr/include/c++/4.8/tr1/bessel_function.tcc \
		/usr/include/c++/4.8/tr1/beta_function.tcc \
		/usr/include/c++/4.8/tr1/ell_integral.tcc \
		/usr/include/c++/4.8/tr1/exp_integral.tcc \
		/usr/include/c++/4.8/tr1/hypergeometric.tcc \
		/usr/include/c++/4.8/tr1/legendre_function.tcc \
		/usr/include/c++/4.8/tr1/modified_bessel_func.tcc \
		/usr/include/c++/4.8/tr1/poly_hermite.tcc \
		/usr/include/c++/4.8/tr1/poly_laguerre.tcc \
		/usr/include/c++/4.8/tr1/riemann_zeta.tcc \
		/usr/include/c++/4.8/tr1/random.h \
		/usr/include/c++/4.8/tr1/random.tcc \
		/usr/include/c++/4.8/parallel/for_each_selectors.h \
		/usr/include/c++/4.8/parallel/partial_sum.h \
		/usr/include/c++/4.8/parallel/algorithm \
		/usr/include/c++/4.8/parallel/algo.h \
		/usr/include/c++/4.8/parallel/sort.h \
		/usr/include/c++/4.8/parallel/checkers.h \
		/usr/include/c++/4.8/parallel/multiway_mergesort.h \
		/usr/include/c++/4.8/parallel/multiway_merge.h \
		/usr/include/c++/4.8/parallel/losertree.h \
		/usr/include/c++/4.8/parallel/multiseq_selection.h \
		/usr/include/c++/4.8/queue \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/include/c++/4.8/debug/deque \
		/usr/include/c++/4.8/profile/deque \
		/usr/include/c++/4.8/bits/stl_queue.h \
		/usr/include/c++/4.8/parallel/quicksort.h \
		/usr/include/c++/4.8/parallel/partition.h \
		/usr/include/c++/4.8/parallel/balanced_quicksort.h \
		/usr/include/c++/4.8/parallel/queue.h \
		/usr/include/c++/4.8/parallel/omp_loop_static.h \
		/usr/include/c++/4.8/parallel/search.h \
		/usr/include/c++/4.8/parallel/random_shuffle.h \
		/usr/include/c++/4.8/parallel/merge.h \
		/usr/include/c++/4.8/parallel/unique_copy.h \
		/usr/include/c++/4.8/parallel/set_operations.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/QString \
		../../../Qt5/5.3/gcc_64/include/QtCore/qstring.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qchar.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qglobal.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qconfig.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qlogging.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qflags.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/include/c++/4.8/atomic \
		/usr/include/c++/4.8/bits/atomic_base.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qmutex.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		src/util.h \
		src/error_enum.h \
		src/collgen_memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bedcoll.o src/bedcoll.cpp

main.o: src/main.cpp ../../../Qt5/5.3/gcc_64/include/QtCore/QCoreApplication \
		../../../Qt5/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qglobal.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qconfig.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/random \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/bits/random.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/bits/random.tcc \
		/usr/include/c++/4.8/numeric \
		/usr/include/c++/4.8/bits/stl_numeric.h \
		/usr/include/c++/4.8/parallel/numeric \
		/usr/include/c++/4.8/parallel/numericfwd.h \
		/usr/include/c++/4.8/parallel/iterator.h \
		/usr/include/c++/4.8/parallel/for_each.h \
		/usr/include/c++/4.8/parallel/par_loop.h \
		/usr/include/c++/4.8/parallel/omp_loop.h \
		/usr/include/c++/4.8/parallel/workstealing.h \
		/usr/include/c++/4.8/parallel/random_number.h \
		/usr/include/c++/4.8/tr1/random \
		/usr/include/c++/4.8/tr1/cmath \
		/usr/include/c++/4.8/tr1/gamma.tcc \
		/usr/include/c++/4.8/tr1/special_function_util.h \
		/usr/include/c++/4.8/tr1/bessel_function.tcc \
		/usr/include/c++/4.8/tr1/beta_function.tcc \
		/usr/include/c++/4.8/tr1/ell_integral.tcc \
		/usr/include/c++/4.8/tr1/exp_integral.tcc \
		/usr/include/c++/4.8/tr1/hypergeometric.tcc \
		/usr/include/c++/4.8/tr1/legendre_function.tcc \
		/usr/include/c++/4.8/tr1/modified_bessel_func.tcc \
		/usr/include/c++/4.8/tr1/poly_hermite.tcc \
		/usr/include/c++/4.8/tr1/poly_laguerre.tcc \
		/usr/include/c++/4.8/tr1/riemann_zeta.tcc \
		/usr/include/c++/4.8/tr1/random.h \
		/usr/include/c++/4.8/tr1/random.tcc \
		/usr/include/c++/4.8/parallel/for_each_selectors.h \
		/usr/include/c++/4.8/parallel/partial_sum.h \
		/usr/include/c++/4.8/parallel/algorithm \
		/usr/include/c++/4.8/parallel/algo.h \
		/usr/include/c++/4.8/parallel/sort.h \
		/usr/include/c++/4.8/parallel/checkers.h \
		/usr/include/c++/4.8/parallel/multiway_mergesort.h \
		/usr/include/c++/4.8/parallel/multiway_merge.h \
		/usr/include/c++/4.8/parallel/losertree.h \
		/usr/include/c++/4.8/parallel/multiseq_selection.h \
		/usr/include/c++/4.8/queue \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/include/c++/4.8/debug/deque \
		/usr/include/c++/4.8/profile/deque \
		/usr/include/c++/4.8/bits/stl_queue.h \
		/usr/include/c++/4.8/parallel/quicksort.h \
		/usr/include/c++/4.8/parallel/partition.h \
		/usr/include/c++/4.8/parallel/balanced_quicksort.h \
		/usr/include/c++/4.8/parallel/queue.h \
		/usr/include/c++/4.8/parallel/omp_loop_static.h \
		/usr/include/c++/4.8/parallel/search.h \
		/usr/include/c++/4.8/parallel/random_shuffle.h \
		/usr/include/c++/4.8/parallel/merge.h \
		/usr/include/c++/4.8/parallel/unique_copy.h \
		/usr/include/c++/4.8/parallel/set_operations.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qlogging.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qflags.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/include/c++/4.8/atomic \
		/usr/include/c++/4.8/bits/atomic_base.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qmutex.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qstring.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qchar.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qobject.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qlist.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qiterator.h \
		/usr/include/c++/4.8/iterator \
		/usr/include/c++/4.8/bits/stream_iterator.h \
		/usr/include/c++/4.8/list \
		/usr/include/c++/4.8/bits/stl_list.h \
		/usr/include/c++/4.8/bits/list.tcc \
		/usr/include/c++/4.8/debug/list \
		/usr/include/c++/4.8/profile/list \
		../../../Qt5/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qisenum.h \
		/usr/include/c++/4.8/map \
		/usr/include/c++/4.8/bits/stl_tree.h \
		/usr/include/c++/4.8/bits/stl_map.h \
		/usr/include/c++/4.8/bits/stl_multimap.h \
		/usr/include/c++/4.8/debug/map \
		/usr/include/c++/4.8/debug/map.h \
		/usr/include/c++/4.8/debug/multimap.h \
		/usr/include/c++/4.8/profile/map \
		/usr/include/c++/4.8/profile/map.h \
		/usr/include/c++/4.8/profile/multimap.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/QString \
		../../../Qt5/5.3/gcc_64/include/QtCore/QDir \
		../../../Qt5/5.3/gcc_64/include/QtCore/qdir.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qfile.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qpair.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qregexp.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/QDebug \
		../../../Qt5/5.3/gcc_64/include/QtCore/qdebug.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qhash.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qmap.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qlocale.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qvariant.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qvector.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qpoint.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qset.h \
		../../../Qt5/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/include/c++/4.8/iostream \
		src/bedcoll.h \
		src/util.h \
		src/error_enum.h \
		src/collgen_memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

