#############################################################################
# Makefile for building: bedcoll
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  bedcollqt.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-clang -o Makefile bedcollqt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -D_FILE_OFFSET_BITS=64 -O2 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I. -I/usr/include/c++/4.8 -I/usr/include/boost
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++
LIBS          = $(SUBLIBS) -lboost_system -lboost_filesystem -lboost_program_options 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/util.cpp \
		src/bedcoll.cpp \
		src/main.cpp 
OBJECTS       = util.o \
		bedcoll.o \
		main.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		bedcollqt.pro \
		bedcollqt.pro
QMAKE_TARGET  = bedcoll
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = bedcoll


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bedcollqt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		bedcollqt.pro
	$(QMAKE) -spec linux-clang -o Makefile bedcollqt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
bedcollqt.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-clang -o Makefile bedcollqt.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/bedcoll1.0.0 || mkdir -p .tmp/bedcoll1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/bedcoll1.0.0/ && (cd `dirname .tmp/bedcoll1.0.0` && $(TAR) bedcoll1.0.0.tar bedcoll1.0.0 && $(COMPRESS) bedcoll1.0.0.tar) && $(MOVE) `dirname .tmp/bedcoll1.0.0`/bedcoll1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/bedcoll1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

util.o: src/util.cpp src/util.h \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/random \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/bits/random.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/bits/random.tcc \
		/usr/include/c++/4.8/numeric \
		/usr/include/c++/4.8/bits/stl_numeric.h \
		/usr/include/c++/4.8/parallel/numeric \
		/usr/include/c++/4.8/parallel/numericfwd.h \
		/usr/include/c++/4.8/parallel/iterator.h \
		/usr/include/c++/4.8/parallel/for_each.h \
		/usr/include/c++/4.8/parallel/par_loop.h \
		/usr/include/c++/4.8/parallel/omp_loop.h \
		/usr/include/c++/4.8/parallel/workstealing.h \
		/usr/include/c++/4.8/parallel/random_number.h \
		/usr/include/c++/4.8/tr1/random \
		/usr/include/c++/4.8/tr1/cmath \
		/usr/include/c++/4.8/tr1/gamma.tcc \
		/usr/include/c++/4.8/tr1/special_function_util.h \
		/usr/include/c++/4.8/tr1/bessel_function.tcc \
		/usr/include/c++/4.8/tr1/beta_function.tcc \
		/usr/include/c++/4.8/tr1/ell_integral.tcc \
		/usr/include/c++/4.8/tr1/exp_integral.tcc \
		/usr/include/c++/4.8/tr1/hypergeometric.tcc \
		/usr/include/c++/4.8/tr1/legendre_function.tcc \
		/usr/include/c++/4.8/tr1/modified_bessel_func.tcc \
		/usr/include/c++/4.8/tr1/poly_hermite.tcc \
		/usr/include/c++/4.8/tr1/poly_laguerre.tcc \
		/usr/include/c++/4.8/tr1/riemann_zeta.tcc \
		/usr/include/c++/4.8/tr1/random.h \
		/usr/include/c++/4.8/tr1/random.tcc \
		/usr/include/c++/4.8/parallel/for_each_selectors.h \
		/usr/include/c++/4.8/parallel/partial_sum.h \
		/usr/include/c++/4.8/parallel/algorithm \
		/usr/include/c++/4.8/parallel/algo.h \
		/usr/include/c++/4.8/parallel/sort.h \
		/usr/include/c++/4.8/parallel/checkers.h \
		/usr/include/c++/4.8/parallel/multiway_mergesort.h \
		/usr/include/c++/4.8/parallel/multiway_merge.h \
		/usr/include/c++/4.8/parallel/losertree.h \
		/usr/include/c++/4.8/parallel/multiseq_selection.h \
		/usr/include/c++/4.8/queue \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/include/c++/4.8/debug/deque \
		/usr/include/c++/4.8/profile/deque \
		/usr/include/c++/4.8/bits/stl_queue.h \
		/usr/include/c++/4.8/parallel/quicksort.h \
		/usr/include/c++/4.8/parallel/partition.h \
		/usr/include/c++/4.8/parallel/balanced_quicksort.h \
		/usr/include/c++/4.8/parallel/queue.h \
		/usr/include/c++/4.8/parallel/omp_loop_static.h \
		/usr/include/c++/4.8/parallel/search.h \
		/usr/include/c++/4.8/parallel/random_shuffle.h \
		/usr/include/c++/4.8/parallel/merge.h \
		/usr/include/c++/4.8/parallel/unique_copy.h \
		/usr/include/c++/4.8/parallel/set_operations.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o src/util.cpp

bedcoll.o: src/bedcoll.cpp src/bedcoll.h \
		/usr/include/c++/4.8/iostream \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/random \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/bits/random.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/bits/random.tcc \
		/usr/include/c++/4.8/numeric \
		/usr/include/c++/4.8/bits/stl_numeric.h \
		/usr/include/c++/4.8/parallel/numeric \
		/usr/include/c++/4.8/parallel/numericfwd.h \
		/usr/include/c++/4.8/parallel/iterator.h \
		/usr/include/c++/4.8/parallel/for_each.h \
		/usr/include/c++/4.8/parallel/par_loop.h \
		/usr/include/c++/4.8/parallel/omp_loop.h \
		/usr/include/c++/4.8/parallel/workstealing.h \
		/usr/include/c++/4.8/parallel/random_number.h \
		/usr/include/c++/4.8/tr1/random \
		/usr/include/c++/4.8/tr1/cmath \
		/usr/include/c++/4.8/tr1/gamma.tcc \
		/usr/include/c++/4.8/tr1/special_function_util.h \
		/usr/include/c++/4.8/tr1/bessel_function.tcc \
		/usr/include/c++/4.8/tr1/beta_function.tcc \
		/usr/include/c++/4.8/tr1/ell_integral.tcc \
		/usr/include/c++/4.8/tr1/exp_integral.tcc \
		/usr/include/c++/4.8/tr1/hypergeometric.tcc \
		/usr/include/c++/4.8/tr1/legendre_function.tcc \
		/usr/include/c++/4.8/tr1/modified_bessel_func.tcc \
		/usr/include/c++/4.8/tr1/poly_hermite.tcc \
		/usr/include/c++/4.8/tr1/poly_laguerre.tcc \
		/usr/include/c++/4.8/tr1/riemann_zeta.tcc \
		/usr/include/c++/4.8/tr1/random.h \
		/usr/include/c++/4.8/tr1/random.tcc \
		/usr/include/c++/4.8/parallel/for_each_selectors.h \
		/usr/include/c++/4.8/parallel/partial_sum.h \
		/usr/include/c++/4.8/parallel/algorithm \
		/usr/include/c++/4.8/parallel/algo.h \
		/usr/include/c++/4.8/parallel/sort.h \
		/usr/include/c++/4.8/parallel/checkers.h \
		/usr/include/c++/4.8/parallel/multiway_mergesort.h \
		/usr/include/c++/4.8/parallel/multiway_merge.h \
		/usr/include/c++/4.8/parallel/losertree.h \
		/usr/include/c++/4.8/parallel/multiseq_selection.h \
		/usr/include/c++/4.8/queue \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/include/c++/4.8/debug/deque \
		/usr/include/c++/4.8/profile/deque \
		/usr/include/c++/4.8/bits/stl_queue.h \
		/usr/include/c++/4.8/parallel/quicksort.h \
		/usr/include/c++/4.8/parallel/partition.h \
		/usr/include/c++/4.8/parallel/balanced_quicksort.h \
		/usr/include/c++/4.8/parallel/queue.h \
		/usr/include/c++/4.8/parallel/omp_loop_static.h \
		/usr/include/c++/4.8/parallel/search.h \
		/usr/include/c++/4.8/parallel/random_shuffle.h \
		/usr/include/c++/4.8/parallel/merge.h \
		/usr/include/c++/4.8/parallel/unique_copy.h \
		/usr/include/c++/4.8/parallel/set_operations.h \
		src/util.h \
		src/error_enum.h \
		src/collgen_memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bedcoll.o src/bedcoll.cpp

main.o: src/main.cpp /usr/include/c++/4.8/iostream \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/bits/istream.tcc \
		src/bedcoll.h \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/random \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/bits/random.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/bits/random.tcc \
		/usr/include/c++/4.8/numeric \
		/usr/include/c++/4.8/bits/stl_numeric.h \
		/usr/include/c++/4.8/parallel/numeric \
		/usr/include/c++/4.8/parallel/numericfwd.h \
		/usr/include/c++/4.8/parallel/iterator.h \
		/usr/include/c++/4.8/parallel/for_each.h \
		/usr/include/c++/4.8/parallel/par_loop.h \
		/usr/include/c++/4.8/parallel/omp_loop.h \
		/usr/include/c++/4.8/parallel/workstealing.h \
		/usr/include/c++/4.8/parallel/random_number.h \
		/usr/include/c++/4.8/tr1/random \
		/usr/include/c++/4.8/tr1/cmath \
		/usr/include/c++/4.8/tr1/gamma.tcc \
		/usr/include/c++/4.8/tr1/special_function_util.h \
		/usr/include/c++/4.8/tr1/bessel_function.tcc \
		/usr/include/c++/4.8/tr1/beta_function.tcc \
		/usr/include/c++/4.8/tr1/ell_integral.tcc \
		/usr/include/c++/4.8/tr1/exp_integral.tcc \
		/usr/include/c++/4.8/tr1/hypergeometric.tcc \
		/usr/include/c++/4.8/tr1/legendre_function.tcc \
		/usr/include/c++/4.8/tr1/modified_bessel_func.tcc \
		/usr/include/c++/4.8/tr1/poly_hermite.tcc \
		/usr/include/c++/4.8/tr1/poly_laguerre.tcc \
		/usr/include/c++/4.8/tr1/riemann_zeta.tcc \
		/usr/include/c++/4.8/tr1/random.h \
		/usr/include/c++/4.8/tr1/random.tcc \
		/usr/include/c++/4.8/parallel/for_each_selectors.h \
		/usr/include/c++/4.8/parallel/partial_sum.h \
		/usr/include/c++/4.8/parallel/algorithm \
		/usr/include/c++/4.8/parallel/algo.h \
		/usr/include/c++/4.8/parallel/sort.h \
		/usr/include/c++/4.8/parallel/checkers.h \
		/usr/include/c++/4.8/parallel/multiway_mergesort.h \
		/usr/include/c++/4.8/parallel/multiway_merge.h \
		/usr/include/c++/4.8/parallel/losertree.h \
		/usr/include/c++/4.8/parallel/multiseq_selection.h \
		/usr/include/c++/4.8/queue \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/include/c++/4.8/debug/deque \
		/usr/include/c++/4.8/profile/deque \
		/usr/include/c++/4.8/bits/stl_queue.h \
		/usr/include/c++/4.8/parallel/quicksort.h \
		/usr/include/c++/4.8/parallel/partition.h \
		/usr/include/c++/4.8/parallel/balanced_quicksort.h \
		/usr/include/c++/4.8/parallel/queue.h \
		/usr/include/c++/4.8/parallel/omp_loop_static.h \
		/usr/include/c++/4.8/parallel/search.h \
		/usr/include/c++/4.8/parallel/random_shuffle.h \
		/usr/include/c++/4.8/parallel/merge.h \
		/usr/include/c++/4.8/parallel/unique_copy.h \
		/usr/include/c++/4.8/parallel/set_operations.h \
		src/util.h \
		src/error_enum.h \
		src/collgen_memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

